INSERT INTO CUSTOMERS (ID,CUSTOMER_NAME,CUSTOMER_PASSWORD,CUSTOMER_EMAIL) VALUES (1,'Menendez6','Menen','pablo@gmail.com');
INSERT INTO CUSTOMERS (ID,CUSTOMER_NAME,CUSTOMER_PASSWORD,CUSTOMER_EMAIL) VALUES (2,'Juan','Juan','juan@hotmail.com');
INSERT INTO CUSTOMERS (ID,CUSTOMER_NAME,CUSTOMER_PASSWORD,CUSTOMER_EMAIL) VALUES (3,'Pedro','Pedro','pedrito19@comillas.es');

INSERT INTO COURSES (ID,COURSE_NAME,SEMESTER,DEGREE) VALUES (1,'Programación en Python',1,'GITT');
INSERT INTO COURSES (ID,COURSE_NAME,SEMESTER,DEGREE) VALUES (2,'Circuitos Eléctricos',2,'GITT');
INSERT INTO COURSES (ID,COURSE_NAME,SEMESTER,DEGREE) VALUES (3,'Circuitos Eléctrónicos',3,'GITT');
INSERT INTO COURSES (ID,COURSE_NAME,SEMESTER,DEGREE) VALUES (4,'Electrónica',5,'GITT');