DROP TABLE IF EXISTS COURSES;
DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE COURSES (
    ID INTEGER IDENTITY PRIMARY KEY,
    COURSE_NAME VARCHAR(255) NOT NULL,
    SEMESTER INTEGER NOT NULL,
    DEGREE VARCHAR(255) NOT NULL
);

CREATE TABLE CUSTOMERS (
    ID INTEGER IDENTITY PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    CUSTOMER_PASSWORD VARCHAR(255) NOT NULL,
    CUSTOMER_EMAIL VARCHAR(255) NOT NULL
);